repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: Black formatter
        types: [ python ]
        require_serial: true
        args: [ "--line-length", "120" ]
