name: AzureLogingTest

on:
  workflow_dispatch:

jobs:
    test_azure_permissions:
        runs-on: ubuntu-latest
        steps:
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
        - run: |
            az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}
            cd back
            docker build -t ey_back:latest .
            docker tag ey_back:latest ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/ey_back:v1
            docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/ey_back:v1

            
