name: AzureLogingTest

on:
  workflow_dispatch:

jobs:
    test_azure_permissions:
        runs-on: ubuntu-latest
        steps:
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
        - run: |
            docker ps -a
            # az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}
            az acr repository list --name ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }} --output table
