name: CI Back

on:
  push:
    branches:
      - '**'
    paths:
      - 'back/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'back/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==24.4.2 isort==5.13.2

    - name: Run Black
      run: |
        black --check back/
    
    - name: Run Isort
      run: |
        isort --check back/


  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        cd back
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Unit tests
      run: |
        cd back
        python -m pytest tests/unit
    - name: Run Integration tests
      run: |
        cd back
        python -m pytest tests/integration
